config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :cars
end

app/models/car.rb
class Car < ParseResource::Base
  fields :plateNumber, :model, :color, :year, :createdAt, :updatedAt, :user

  belongs_to :user, :class_name => 'User'

  validates_presence_of :plateNumber, :model, :color, :year
end

app/models/user.rb
class User < ParseResource::Base
  fields :username, :password, :email, :name, :url, :facebookUrl, :phoneNumber

  validates_presence_of :username, :email, :name, :phoneNumber
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index

  end

  def show

  end

  def create

  end

  def update

  end

  def destroy

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show

  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def update

  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FrocBorneo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="ui column grid">
    <div class="column">
      <%= render "shared/menu" %>
      <%= semantic_flash %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/shared/_menu.html.erb
<div class="ui menu">
  <a class="active item">
    <i class="home icon"></i> FrocBorneo
  </a>
  <a href="<%= users_path %>" class="item">
    <i class="user icon"></i> Users
  </a>
  <a href="<%= cars_path %>" class="item">
    <i class="shipping icon"></i> Cars
  </a>
  <div class="right menu">
    <div class="item">
      <div class="ui transparent icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="ui segment">
  <form class="ui form">
    <h4 class="ui dividing header">Personal Information</h4>
    <div class="required field">
      <label>Name</label>
      <input type="text" name="name" placeholder="Name">
    </div>
    <div class="required field">
      <label>Email</label>
      <input type="text" name="email" placeholder="Email Address">
    </div>
    <div class="required field">
      <label>Phone Number</label>
      <input type="text" name="phoneNumber" placeholder="Phone Number">
    </div>
    <div class="required field">
      <label>Facebook URL</label>
      <input type="text" name="facebookUrl" placeholder="Facebook URL">
    </div>
    <h4 class="ui dividing header">Login Information</h4>
    <div class="required field">
      <label>Username</label>
      <input type="text" name="username" placeholder="Username">
    </div>
    <div class="required field">
      <label>Password</label>
      <input type="password" name="password" placeholder="Password">
    </div>
    <div class="ui submit button">Add User</div>
  </form>
</div>

app/views/users/index.html.erb
<div class="ui segment">
  <table class="ui table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Phone Number</th>
        <th>E-mail address</th>
        <th>Facebook URL</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.phoneNumber %></td>
          <td><%= user.email %></td>
          <td><%= link_to user.facebookUrl, user.facebookUrl %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="ui segment">
  <%= form_for(@user, method: :post, html: { class: "ui form" }) do |f| %>
    <h4 class="ui dividing header">Personal Information</h4>
    <div class="required field">
      <label>Name</label>
      <%= f.text_field :name %>
    </div>
    <div class="required field">
      <label>Email</label>
      <%= f.text_field :email %>
    </div>
    <div class="required field">
      <label>Phone Number</label>
      <%= f.text_field :phoneNumber %>
    </div>
    <div class="required field">
      <label>Facebook URL</label>
      <%= f.text_field :facebookUrl %>
    </div>
    <h4 class="ui dividing header">Login Information</h4>
    <div class="required field">
      <label>Username</label>
      <%= f.text_field :username %>
    </div>
    <div class="required field">
      <label>Password</label>
      <%= f.password_field :password %>
    </div>
    <input type="submit" class="ui submit button" value="Add User" />
  <% end %>
</div>